{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "product-a-service.fullname" . }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "product-a-service.fullname" . }}
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
  tls:
{{- range .Values.ingress.tls }}
    - hosts:
{{ toYaml .hosts | indent 6 }}
      secretName: {{ .secretName }}
{{- end }}
{{- end }}
